// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfpspkainlidjryigxvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcHNwa2FpbmxpZGpyeWlneHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDY3MDMsImV4cCI6MjA3MjEyMjcwM30.zdmTWLqM8zv4p3_IPnUjkdxgL35IIOCBM2NYdDpFy54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});